apiVersion: apps/v1
kind: Deployment
metadata:
  name: nowebapp-greendeployment
  labels:
    app: nowwebapp
    version: "1.1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nowwebapp 
      version: "1.1"
  template:
    metadata:
      labels:
        app: nowwebapp 
        version: "1.1"
    spec:
      containers:
      - name: nowwebapp 
        image: 501387525279.dkr.ecr.us-east-1.amazonaws.com/now:version1.1
        ports:
        - containerPort: 80